[project]
site_url = "https://IT-Amine.github.io/cub"
site_name = "Cub Documentation"
site_description = "Documentation du contexte CUB du BTS SIO Paul-Louis Courier."
site_author = "Amine Kada"

copyright = "Copyright &copy; 2026 Amine Kada"

repo_url = "https://github.com/IT-Amine/cub"
repo_name = "IT-Amine/cub"
edit_uri = "edit/main/docs/"

nav = [
  { "Accueil CUB" = "index.md" },
  { "Contexte" = [
      { "Description de l'infrastructure" = "description.md" },
      { "Plan de l'infrastructure CUB" = "plan.md" },
      { "Contexte CUB - BTS SIO" = "presentation.md" }
  ] },
  { "Reseau" = [
      { "Administration et supervision des Réseaux" = "reseau/index.md" },
      { "Vlsm Routage" = "reseau/vlsm-routage.md" },
      { "Cisco" = [
          { "Configurations Cisco (CUB)" = "reseau/cisco/configurations/commande-cub.md" },
          { "Implémentation du Relais DHCP sur équipement Cisco" = "reseau/cisco/dhcp/implementation-relais-dhcp-cisco.md" },
          { "Implémentation du NAT (PAT) sur un routeur Cisco" = "reseau/cisco/nat/configuration-nat-routeur-cisco.md" },
          { "Fiche recette - Commutateur L3" = "reseau/cisco/recettes/recette-commutateur-l3-cisco.md" },
          { "Implémentation du routage statique (Cisco)" = "reseau/cisco/routage/implementation-routage-statique-cisco.md" },
          { "Implémentation des mots de passe par niveau d'accès (Cisco)" = "reseau/cisco/securite/implementation-mots-de-passe-niveau-acces.md" },
          { "Implémentation du SSH sur un commutateur Cisco" = "reseau/cisco/ssh/configuration-ssh-commutateur-cisco.md" },
          { "Implémentation du SSH sur un routeur Cisco" = "reseau/cisco/ssh/configuration-ssh-routeur-cisco.md" },
          { "Implémentation du VTP sur commutateur Cisco" = "reseau/cisco/vtp/implementation-vtp-cisco.md" }
      ] }
  ] },
  { "Ressources" = [
      { "Configurations" = "ressources/configurations.md" },
      { "Gestion de versions avec Git & GitHub" = "ressources/git.md" },
      { "Ressources" = "ressources/index.md" },
      { "Plan d'adressage" = "ressources/plan-adressage.md" },
      { "Schémas" = "ressources/schemas.md" },
      { "Tables NAT" = "ressources/tables-nat.md" },
      { "Tables de routage" = "ressources/tables-routage.md" }
  ] },
  { "Securite" = [
      { "Cybersecurite Cub" = "securite/cybersecurite-cub.md" },
      { "Cybersécurité" = "securite/index.md" },
      { "Stormshield" = [
          { "Résolution de l'erreur d'objets dérivés sur ethernet0" = "securite/stormshield/problemes/resolution-erreur-derives-ethernet.md" },
          { "Configuration d'une interface sur Stormshield avec la configuration IP" = "securite/stormshield/procedures/configuration-interface-stormshield.md" },
          { "Configuration du NAT sur Stormshield" = "securite/stormshield/procedures/configuration-nat-stormshield.md" },
          { "Configuration du routage sur stormshield" = "securite/stormshield/procedures/configuration-routage-stormshield.md" },
          { "Configuration d'une sous-interface (VLAN 802.1Q) sur Stormshield" = "securite/stormshield/procedures/configuration-sous-interface-stormshield.md" },
          { "Sauvegarde de la configuration sur Stormshield" = "securite/stormshield/procedures/sauvegarde-configuration-stormshield.md" },
          { "Fiche Recette : Pare-feu Stormshield" = "securite/stormshield/recettes/recette-pare-feu-stormshield.md" }
      ] }
  ] },
  { "Services" = [
      { "Fiche de révision : Exploitation des services Debian" = "services/exploitation-services.md" },
      { "Exploitation des services" = "services/index.md" },
      { "Bastion" = [
          { "Activité 1 : Réflexion sur le Bastion" = "services/bastion/activite1-reflexion-bastion.md" },
          { "Gestion des utilisateurs et des sessions (Guacamole)" = "services/bastion/guacamole-configuration.md" },
          { "Bastion Guacamole (Docker)" = "services/bastion/guacamole-installation.md" }
      ] },
      { "Communs" = [
          { "Configuration du hostname" = "services/communs/configuration-hostname-debian.md" },
          { "Installation des paquets communs Debian" = "services/communs/installation-paquets-commun-debian.md" }
      ] },
      { "Dns" = [
          { "Déploiement DNS Esclave (ns1)" = "services/dns/config-dns-autoritaire.md" },
          { "Configuration DNS Récursif" = "services/dns/config-dns-recursif.md" },
          { "Fiche Recette : DNS Autoritaire Esclave" = "services/dns/recette-dns-autoritaire.md" },
          { "Fiche Recette : DNS Récursif (Unbound)" = "services/dns/recette-dns-recursif.md" }
      ] },
      { "Etckeeper" = [
          { "Installation et configuration de Etckeeper" = "services/etckeeper/installation-configuration-etckeeper.md" }
      ] },
      { "Totp" = [
          { "Mise en place de l'authentification TOTP sur Debian" = "services/totp/installation-configuration-totp.md" }
      ] }
  ] },
  { "Windows" = [
      { "Administration Windows" = "windows/index.md" },
      { "Core" = [
          { "AD1 Core" = "windows/core/config-ad.md" },
          { "DHCP Core" = "windows/core/config-dhcp.md" },
          { "Configuration Windows Core" = "windows/core/configuration-windows-core.md" },
          { "Procédure : Extension du volume système (C:) sur machine virtuelle" = "windows/core/extension-volume-windows.md" }
      ] },
      { "Wac" = [
          { "Ajout d'un serveur dans WAC" = "windows/wac/ajout-serveur-wac.md" },
          { "Création d'un compte WAC" = "windows/wac/creation-compte-administrer-wac.md" },
          { "Installation de WAC" = "windows/wac/installation-wac.md" }
      ] }
  ] }
]

# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
favicon = "assets/banniere-cub.png"
language = "fr"
logo = "assets/banniere-cub.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# [project.theme.icon]
# logo = "lucide/smile"

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/IT-Amine"

[project.markdown_extensions]
tables = {}
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}
