[project]
site_url = "https://IT-Amine.github.io/cub"
site_name = "Cub Documentation"
site_description = "Documentation du contexte CUB du BTS SIO Paul-Louis Courier."
site_author = "Amine Kada"


nav = [
  { "GÉNÉRAL - CUB" = [
    "index.md",
    "General - CUB/presentation.md",
    "General - CUB/description.md",
    "General - CUB/plan.md"
  ]},
  { "Réseau" = [
    "reseau/index.md",
    "reseau/vlsm-routage.md",
    { "Cisco" = [
      { "Configurations" = ["reseau/cisco/configurations/commande-cub.md"] },
      { "Recettes" = ["reseau/cisco/recettes/recette-commutateur-l3-cisco.md"] },
      { "Sécurité" = ["reseau/cisco/securite/implementation-mots-de-passe-niveau-acces.md"] },
      { "NAT" = ["reseau/cisco/nat/configuration-nat-routeur-cisco.md"] },
      { "SSH" = [
        "reseau/cisco/ssh/configuration-ssh-routeur-cisco.md",
        "reseau/cisco/ssh/configuration-ssh-commutateur-cisco.md"
      ]},
      { "VTP" = ["reseau/cisco/vtp/implementation-vtp-cisco.md"] },
      { "DHCP" = ["reseau/cisco/dhcp/implementation-relais-dhcp-cisco.md"] },
      { "Routage" = ["reseau/cisco/routage/implementation-routage-statique-cisco.md"] }
    ]}
  ]},
  { "Sécurité" = [
    "securite/index.md",
    "securite/cybersecurite-cub.md",
    { "Stormshield" = [
      { "Procédures" = [
        "securite/stormshield/procedures/configuration-sous-interface-stormshield.md",
        "securite/stormshield/procedures/configuration-interface-stormshield.md",
        "securite/stormshield/procedures/configuration-nat-stormshield.md",
        "securite/stormshield/procedures/sauvegarde-configuration-stormshield.md",
        "securite/stormshield/procedures/configuration-routage-stormshield.md"
      ]},
      { "Recettes" = ["securite/stormshield/recettes/recette-pare-feu-stormshield.md"] },
      { "Problèmes" = ["securite/stormshield/problemes/resolution-erreur-derives-ethernet.md"] }
    ]},
    { "Bastion" = [
      "securite/bastion/installation-guacamole.md",
      "securite/bastion/configuration-totp.md",
      "securite/bastion/configuration-enregistrement-connexions.md",
      "securite/bastion/creer-connexion-rdp-windows.md",
      "securite/bastion/creer-connexion-ssh-linux.md",
      "securite/bastion/creer-groupe-guacamole.md",
      "securite/bastion/creer-utilisateur-guacamole.md"
    ]},
    { "UFW" = ["securite/ufw/installation-configuration-ufw.md"] }
  ]},
  { "Services" = [
    "services/index.md",
    "services/exploitation-services.md",
    { "Communs" = [
      "services/communs/installation-paquets-commun-debian.md",
      "services/communs/configuration-hostname-debian.md"
    ]},
    { "DNS" = [
      "services/dns/recette-dns-recursif.md",
      "services/dns/creation-delegation-dns.md",
      "services/dns/recette-dns-autoritaire.md",
      "services/dns/config-dns-recursif.md",
      "services/dns/config-dns-autoritaire.md",
      "services/dns/config-dns-maitre.md"
    ]},
    { "Etckeeper" = ["services/etckeeper/installation-configuration-etckeeper.md"] },
    { "GLPI" = [
      "services/glpi/installation-glpi.md",
      "services/glpi/creation-gestion-entites-glpi.md",
      "services/glpi/creer-ordinateur-manuellement-glpi.md",
      "services/glpi/creer-categories-itil.md",
      "services/glpi/creer-utilisateur-glpi.md",
      "services/glpi/inventaire-automatise-glpi.md"
    ]},
    { "TOTP" = ["services/totp/installation-configuration-totp.md"] }
  ]},
  { "Windows" = [
    "windows/index.md",
    { "Core" = [
      "windows/core/configuration-windows-core.md",
      "windows/core/config-ad.md",
      "windows/core/config-dhcp.md",
      "windows/core/extension-volume-windows.md"
    ]},
    { "PowerShell" = [
      "windows/powershell/fondamentaux-powershell.md",
      "windows/powershell/gestion-utilisateurs-locaux-active-directory.md",
      "windows/powershell/gestion-dossiers-fichiers-powershell.md",
      "windows/powershell/variables-proprietes-methodes-powershell.md",
      "windows/powershell/documents.md"
    ]},
    { "Windows Admin Center" = [
      "windows/wac/installation-wac.md",
      "windows/wac/creation-compte-administrer-wac.md",
      "windows/wac/ajout-serveur-wac.md"
    ]}
  ]},
  { "Ressources" = [
    "ressources/index.md",
    "ressources/schemas.md",
    "ressources/plan-adressage.md",
    "ressources/tables-routage.md",
    "ressources/tables-nat.md",
    "ressources/configurations.md",
    "ressources/git.md"
  ]}
]


copyright = "Copyright &copy; 2026 Amine Kada"

repo_url = "https://github.com/IT-Amine/cub"
repo_name = "IT-Amine/cub"
edit_uri = "edit/main/docs/"

# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
favicon = "assets/banniere-cub.png"
language = "fr"
logo = "assets/banniere-cub.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# [project.theme.icon]
# logo = "lucide/smile"

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/IT-Amine"

[project.markdown_extensions]
tables = {}
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}
